# Generated by Django 4.2.5 on 2023-10-22 22:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuarioapp',
            name='is_staff',
            field=models.BooleanField(default=False),
        ),
    ]
