# Generated by Django 4.2.5 on 2023-10-22 22:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_api', '0002_usuarioapp_is_staff'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuarioapp',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
    ]
