# Generated by Django 4.2.5 on 2023-09-16 22:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Computer',
            fields=[
                ('id_computer', models.BigAutoField(auto_created=True, primary_key=True, serialize=False)),
                ('tip_computador', models.CharField(max_length=50)),
                ('modelo', models.CharField(max_length=50)),
                ('marca', models.CharField(max_length=50)),
                ('tip_memoria', models.CharField(max_length=50)),
                ('cap_memoria', models.CharField(max_length=50)),
                ('put_memoria', models.BigIntegerField(null=True)),
                ('tip_disco', models.CharField(max_length=50)),
                ('cap_disco', models.CharField(max_length=50)),
                ('put_disco', models.BigIntegerField(null=True)),
                ('grafica', models.BooleanField()),
                ('tip_grafica', models.CharField(max_length=50)),
                ('cap_grafica', models.CharField(max_length=50)),
                ('put_grafica', models.BigIntegerField()),
                ('procesador', models.CharField(max_length=50)),
                ('vel_procesador', models.CharField(max_length=50)),
                ('put_procesador', models.BigIntegerField()),
            ],
        ),
    ]
