# Generated by Django 4.2.5 on 2023-09-17 02:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_computer_sistema_operativo'),
    ]

    operations = [
        migrations.AddField(
            model_name='computer',
            name='costo',
            field=models.FloatField(null=True),
        ),
    ]
