# Generated by Django 4.2.5 on 2023-09-17 02:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_computer_costo'),
    ]

    operations = [
        migrations.AddField(
            model_name='computer',
            name='proposito',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
