# Generated by Django 4.2.5 on 2023-09-17 02:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_computer_proposito'),
    ]

    operations = [
        migrations.AddField(
            model_name='computer',
            name='tienda',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
