# Generated by Django 4.2.5 on 2023-10-17 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_alter_computer_tienda'),
    ]

    operations = [
        migrations.AlterField(
            model_name='computer',
            name='img',
            field=models.ImageField(null=True, upload_to='piproyecto/files/covers'),
        ),
    ]
