# Generated by Django 4.2.5 on 2023-10-22 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_alter_computer_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='computer',
            name='img',
            field=models.CharField(max_length=500, null=True),
        ),
    ]
